### ISSUE TITLE
Problem in tuner_r82xx.c: Call to undeclared function rtlsdr_check_dongle_model

### ISSUE THREAD

**Issue by Mr-Precise** [rtlsdrblog/rtl-sdr-blog-minimal#1]
clang compile error in:
https://github.com/rtlsdrblog/rtl-sdr-blog-minimal/blob/b1cf775a1b9b6ffbb425af1e55c1772e35406939/src/tuner_r82xx.c#L1106
Call to undeclared function 'rtlsdr_check_dongle_model'; ISO C99 and later do not support implicit function declarations clang (-Wimplicit-function-declaration)
Yes, GCC compiles this with a warning.
_thoughts.._
Adding this code before"r82xx_set_freq"
int rtlsdr_check_dongle_model(struct r82xx_priv *priv, char *manufact_check, char *product_check);
I think it will be a bad or not working solution... but it worked with clang

**Comment by rtlsdrblog** [comment]
Should be fixed now in 8c74bf8753b9729be9bc5130957e0d33fe9c4674
